name: sqgan_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - torchvision
  - pytorch-gpu
  - pytorch
  - pytorch-lightning=1.5.6
  - omegaconf
  - pytz
  - ca-certificates
  - openssl
  - requests
  - einops
  - certifi
  - scikit-learn
  - wandb
  - matplotlib
  - easydict
  - pandas
  - blobfile
  - pip
  - pip:
      - pytorch-fid

